# Generated by Django 4.1.3 on 2022-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farminformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workerspayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('PaymentType', models.CharField(max_length=255)),
                ('Mobilenumber', models.BigIntegerField(verbose_name=10)),
            ],
        ),
    ]
